spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/template/
    suffix: .html
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /fbmp-socket
socket:
  port: 9000 #socket端口
